version: "1"

services:
  app1:
    build: ./app1
    ports:
      - "3000:3000"
    # volumes:
    #   - ./app1:/
    command: node server.js

  app2:
    build: ./app2
    ports:
      - "3001:3000"
    # volumes:
    #   - ./app2:/
    command: node server.js
